theme: jekyll-theme-minimal

title: KFA Australia
description: Bookmark this to keep an eye for updates!
logo: kfa-logo.png

show_downloads: false

github:
  is_project_page: false
  is_user_page: false
